// <auto-generated />
namespace Test_Web_Forms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddLeaveBalanceColumnToLeave : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLeaveBalanceColumnToLeave));
        
        string IMigrationMetadata.Id
        {
            get { return "202401121035119_AddLeaveBalanceColumnToLeave"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
