//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Test_Web_Forms.TenderCard {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TenderCard_Binding", Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class TenderCard_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_Control13OperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_Control12OperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_Tender_Scope_of_WorkOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_Tender_AddendumOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_CommitteeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_AddendumOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TenderCard_Service() {
            this.Url = global::Test_Web_Forms.Properties.Settings.Default.Test_Web_Forms_TenderCard_TenderCard_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event Delete_Control13CompletedEventHandler Delete_Control13Completed;
        
        /// <remarks/>
        public event Delete_Control12CompletedEventHandler Delete_Control12Completed;
        
        /// <remarks/>
        public event Delete_Tender_Scope_of_WorkCompletedEventHandler Delete_Tender_Scope_of_WorkCompleted;
        
        /// <remarks/>
        public event Delete_Tender_AddendumCompletedEventHandler Delete_Tender_AddendumCompleted;
        
        /// <remarks/>
        public event Delete_CommitteeCompletedEventHandler Delete_CommitteeCompleted;
        
        /// <remarks/>
        public event Delete_AddendumCompletedEventHandler Delete_AddendumCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("TenderCard")]
        public TenderCard Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((TenderCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("TenderCard")]
        public TenderCard ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((TenderCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TenderCard[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] TenderCard_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((TenderCard[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(TenderCard_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(TenderCard_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref TenderCard TenderCard) {
            object[] results = this.Invoke("Create", new object[] {
                        TenderCard});
            TenderCard = ((TenderCard)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(TenderCard TenderCard) {
            this.CreateAsync(TenderCard, null);
        }
        
        /// <remarks/>
        public void CreateAsync(TenderCard TenderCard, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        TenderCard}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref TenderCard[] TenderCard_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        TenderCard_List});
            TenderCard_List = ((TenderCard[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(TenderCard[] TenderCard_List) {
            this.CreateMultipleAsync(TenderCard_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(TenderCard[] TenderCard_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        TenderCard_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref TenderCard TenderCard) {
            object[] results = this.Invoke("Update", new object[] {
                        TenderCard});
            TenderCard = ((TenderCard)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(TenderCard TenderCard) {
            this.UpdateAsync(TenderCard, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(TenderCard TenderCard, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        TenderCard}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref TenderCard[] TenderCard_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        TenderCard_List});
            TenderCard_List = ((TenderCard[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(TenderCard[] TenderCard_List) {
            this.UpdateMultipleAsync(TenderCard_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(TenderCard[] TenderCard_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        TenderCard_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Delete_Control13", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Delete_Control13_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Control13_Result")]
        public bool Delete_Control13(string Control13_Key) {
            object[] results = this.Invoke("Delete_Control13", new object[] {
                        Control13_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_Control13Async(string Control13_Key) {
            this.Delete_Control13Async(Control13_Key, null);
        }
        
        /// <remarks/>
        public void Delete_Control13Async(string Control13_Key, object userState) {
            if ((this.Delete_Control13OperationCompleted == null)) {
                this.Delete_Control13OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_Control13OperationCompleted);
            }
            this.InvokeAsync("Delete_Control13", new object[] {
                        Control13_Key}, this.Delete_Control13OperationCompleted, userState);
        }
        
        private void OnDelete_Control13OperationCompleted(object arg) {
            if ((this.Delete_Control13Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_Control13Completed(this, new Delete_Control13CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Delete_Control12", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Delete_Control12_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Control12_Result")]
        public bool Delete_Control12(string Control12_Key) {
            object[] results = this.Invoke("Delete_Control12", new object[] {
                        Control12_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_Control12Async(string Control12_Key) {
            this.Delete_Control12Async(Control12_Key, null);
        }
        
        /// <remarks/>
        public void Delete_Control12Async(string Control12_Key, object userState) {
            if ((this.Delete_Control12OperationCompleted == null)) {
                this.Delete_Control12OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_Control12OperationCompleted);
            }
            this.InvokeAsync("Delete_Control12", new object[] {
                        Control12_Key}, this.Delete_Control12OperationCompleted, userState);
        }
        
        private void OnDelete_Control12OperationCompleted(object arg) {
            if ((this.Delete_Control12Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_Control12Completed(this, new Delete_Control12CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Delete_Tender_Scope_of_Work", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Delete_Tender_Scope_of_Work_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Tender_Scope_of_Work_Result")]
        public bool Delete_Tender_Scope_of_Work(string Tender_Scope_of_Work_Key) {
            object[] results = this.Invoke("Delete_Tender_Scope_of_Work", new object[] {
                        Tender_Scope_of_Work_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_Tender_Scope_of_WorkAsync(string Tender_Scope_of_Work_Key) {
            this.Delete_Tender_Scope_of_WorkAsync(Tender_Scope_of_Work_Key, null);
        }
        
        /// <remarks/>
        public void Delete_Tender_Scope_of_WorkAsync(string Tender_Scope_of_Work_Key, object userState) {
            if ((this.Delete_Tender_Scope_of_WorkOperationCompleted == null)) {
                this.Delete_Tender_Scope_of_WorkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_Tender_Scope_of_WorkOperationCompleted);
            }
            this.InvokeAsync("Delete_Tender_Scope_of_Work", new object[] {
                        Tender_Scope_of_Work_Key}, this.Delete_Tender_Scope_of_WorkOperationCompleted, userState);
        }
        
        private void OnDelete_Tender_Scope_of_WorkOperationCompleted(object arg) {
            if ((this.Delete_Tender_Scope_of_WorkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_Tender_Scope_of_WorkCompleted(this, new Delete_Tender_Scope_of_WorkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Delete_Tender_Addendum", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Delete_Tender_Addendum_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Tender_Addendum_Result")]
        public bool Delete_Tender_Addendum(string Tender_Addendum_Key) {
            object[] results = this.Invoke("Delete_Tender_Addendum", new object[] {
                        Tender_Addendum_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_Tender_AddendumAsync(string Tender_Addendum_Key) {
            this.Delete_Tender_AddendumAsync(Tender_Addendum_Key, null);
        }
        
        /// <remarks/>
        public void Delete_Tender_AddendumAsync(string Tender_Addendum_Key, object userState) {
            if ((this.Delete_Tender_AddendumOperationCompleted == null)) {
                this.Delete_Tender_AddendumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_Tender_AddendumOperationCompleted);
            }
            this.InvokeAsync("Delete_Tender_Addendum", new object[] {
                        Tender_Addendum_Key}, this.Delete_Tender_AddendumOperationCompleted, userState);
        }
        
        private void OnDelete_Tender_AddendumOperationCompleted(object arg) {
            if ((this.Delete_Tender_AddendumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_Tender_AddendumCompleted(this, new Delete_Tender_AddendumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Delete_Committee", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Delete_Committee_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Committee_Result")]
        public bool Delete_Committee(string Committee_Key) {
            object[] results = this.Invoke("Delete_Committee", new object[] {
                        Committee_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_CommitteeAsync(string Committee_Key) {
            this.Delete_CommitteeAsync(Committee_Key, null);
        }
        
        /// <remarks/>
        public void Delete_CommitteeAsync(string Committee_Key, object userState) {
            if ((this.Delete_CommitteeOperationCompleted == null)) {
                this.Delete_CommitteeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_CommitteeOperationCompleted);
            }
            this.InvokeAsync("Delete_Committee", new object[] {
                        Committee_Key}, this.Delete_CommitteeOperationCompleted, userState);
        }
        
        private void OnDelete_CommitteeOperationCompleted(object arg) {
            if ((this.Delete_CommitteeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_CommitteeCompleted(this, new Delete_CommitteeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/tendercard:Delete_Addendum", RequestNamespace="urn:microsoft-dynamics-schemas/page/tendercard", ResponseElementName="Delete_Addendum_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/tendercard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Addendum_Result")]
        public bool Delete_Addendum(string Addendum_Key) {
            object[] results = this.Invoke("Delete_Addendum", new object[] {
                        Addendum_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_AddendumAsync(string Addendum_Key) {
            this.Delete_AddendumAsync(Addendum_Key, null);
        }
        
        /// <remarks/>
        public void Delete_AddendumAsync(string Addendum_Key, object userState) {
            if ((this.Delete_AddendumOperationCompleted == null)) {
                this.Delete_AddendumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_AddendumOperationCompleted);
            }
            this.InvokeAsync("Delete_Addendum", new object[] {
                        Addendum_Key}, this.Delete_AddendumOperationCompleted, userState);
        }
        
        private void OnDelete_AddendumOperationCompleted(object arg) {
            if ((this.Delete_AddendumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_AddendumCompleted(this, new Delete_AddendumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class TenderCard {
        
        private string keyField;
        
        private string noField;
        
        private string titleField;
        
        private string requisition_NoField;
        
        private string procurement_Plan_NoField;
        
        private System.DateTime creation_DateField;
        
        private bool creation_DateFieldSpecified;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string user_IDField;
        
        private string categoryField;
        
        private string reference_NoField;
        
        private System.DateTime quotation_DeadlineField;
        
        private bool quotation_DeadlineFieldSpecified;
        
        private System.DateTime expected_Closing_TimeField;
        
        private bool expected_Closing_TimeFieldSpecified;
        
        private System.DateTime committee_Submission_DateField;
        
        private bool committee_Submission_DateFieldSpecified;
        
        private System.DateTime committee_Submission_TimeField;
        
        private bool committee_Submission_TimeFieldSpecified;
        
        private System.DateTime termination_DateField;
        
        private bool termination_DateFieldSpecified;
        
        private string termination_CodeField;
        
        private string termination_ReasonField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private Tender_Type tender_TypeField;
        
        private bool tender_TypeFieldSpecified;
        
        private bool submitted_To_PortalField;
        
        private bool submitted_To_PortalFieldSpecified;
        
        private Process_Type process_TypeField;
        
        private bool process_TypeFieldSpecified;
        
        private Procurement_Documents_Sub_Form[] control13Field;
        
        private Procurement_Request_Lines[] control12Field;
        
        private Tender_Scope_of_Work[] tender_Scope_of_WorkField;
        
        private Tender_Addendum[] tender_AddendumField;
        
        private Opening_Committee_Members[] committeeField;
        
        private Addendum_Registration[] addendumField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Requisition_No {
            get {
                return this.requisition_NoField;
            }
            set {
                this.requisition_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Procurement_Plan_No {
            get {
                return this.procurement_Plan_NoField;
            }
            set {
                this.procurement_Plan_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Creation_Date {
            get {
                return this.creation_DateField;
            }
            set {
                this.creation_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Creation_DateSpecified {
            get {
                return this.creation_DateFieldSpecified;
            }
            set {
                this.creation_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string Reference_No {
            get {
                return this.reference_NoField;
            }
            set {
                this.reference_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Quotation_Deadline {
            get {
                return this.quotation_DeadlineField;
            }
            set {
                this.quotation_DeadlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quotation_DeadlineSpecified {
            get {
                return this.quotation_DeadlineFieldSpecified;
            }
            set {
                this.quotation_DeadlineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Expected_Closing_Time {
            get {
                return this.expected_Closing_TimeField;
            }
            set {
                this.expected_Closing_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Expected_Closing_TimeSpecified {
            get {
                return this.expected_Closing_TimeFieldSpecified;
            }
            set {
                this.expected_Closing_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Committee_Submission_Date {
            get {
                return this.committee_Submission_DateField;
            }
            set {
                this.committee_Submission_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Committee_Submission_DateSpecified {
            get {
                return this.committee_Submission_DateFieldSpecified;
            }
            set {
                this.committee_Submission_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Committee_Submission_Time {
            get {
                return this.committee_Submission_TimeField;
            }
            set {
                this.committee_Submission_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Committee_Submission_TimeSpecified {
            get {
                return this.committee_Submission_TimeFieldSpecified;
            }
            set {
                this.committee_Submission_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Termination_Date {
            get {
                return this.termination_DateField;
            }
            set {
                this.termination_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Termination_DateSpecified {
            get {
                return this.termination_DateFieldSpecified;
            }
            set {
                this.termination_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Termination_Code {
            get {
                return this.termination_CodeField;
            }
            set {
                this.termination_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Termination_Reason {
            get {
                return this.termination_ReasonField;
            }
            set {
                this.termination_ReasonField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Tender_Type Tender_Type {
            get {
                return this.tender_TypeField;
            }
            set {
                this.tender_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tender_TypeSpecified {
            get {
                return this.tender_TypeFieldSpecified;
            }
            set {
                this.tender_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Submitted_To_Portal {
            get {
                return this.submitted_To_PortalField;
            }
            set {
                this.submitted_To_PortalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Submitted_To_PortalSpecified {
            get {
                return this.submitted_To_PortalFieldSpecified;
            }
            set {
                this.submitted_To_PortalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Process_Type Process_Type {
            get {
                return this.process_TypeField;
            }
            set {
                this.process_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Process_TypeSpecified {
            get {
                return this.process_TypeFieldSpecified;
            }
            set {
                this.process_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Procurement_Documents_Sub_Form[] Control13 {
            get {
                return this.control13Field;
            }
            set {
                this.control13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Procurement_Request_Lines[] Control12 {
            get {
                return this.control12Field;
            }
            set {
                this.control12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Tender_Scope_of_Work[] Tender_Scope_of_Work {
            get {
                return this.tender_Scope_of_WorkField;
            }
            set {
                this.tender_Scope_of_WorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Tender_Addendum[] Tender_Addendum {
            get {
                return this.tender_AddendumField;
            }
            set {
                this.tender_AddendumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Opening_Committee_Members[] Committee {
            get {
                return this.committeeField;
            }
            set {
                this.committeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Addendum_Registration[] Addendum {
            get {
                return this.addendumField;
            }
            set {
                this.addendumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum Status {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Archived,
        
        /// <remarks/>
        Opening,
        
        /// <remarks/>
        Pending_Approval,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Terminated,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Released,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum Tender_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Restricted,
        
        /// <remarks/>
        Direct,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum Process_Type {
        
        /// <remarks/>
        _quote__blank__quote_,
        
        /// <remarks/>
        Direct,
        
        /// <remarks/>
        Tender,
        
        /// <remarks/>
        Low_Value,
        
        /// <remarks/>
        Restricted,
        
        /// <remarks/>
        Framework_Agreement,
        
        /// <remarks/>
        RFQ,
        
        /// <remarks/>
        RFP,
        
        /// <remarks/>
        EOI,
        
        /// <remarks/>
        Supplier_Categories,
        
        /// <remarks/>
        Framework_Quotes,
        
        /// <remarks/>
        FA_Disposal_Quote,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class Procurement_Documents_Sub_Form {
        
        private string keyField;
        
        private string document_CodeField;
        
        private string document_NameField;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private bool checkedField;
        
        private bool checkedFieldSpecified;
        
        private string quote_NoField;
        
        private int line_NoField;
        
        private bool line_NoFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Document_Code {
            get {
                return this.document_CodeField;
            }
            set {
                this.document_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Document_Name {
            get {
                return this.document_NameField;
            }
            set {
                this.document_NameField = value;
            }
        }
        
        /// <remarks/>
        public bool Mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckedSpecified {
            get {
                return this.checkedFieldSpecified;
            }
            set {
                this.checkedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Quote_No {
            get {
                return this.quote_NoField;
            }
            set {
                this.quote_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Line_No {
            get {
                return this.line_NoField;
            }
            set {
                this.line_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_NoSpecified {
            get {
                return this.line_NoFieldSpecified;
            }
            set {
                this.line_NoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class TenderCard_Filter {
        
        private TenderCard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public TenderCard_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum TenderCard_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Title,
        
        /// <remarks/>
        Requisition_No,
        
        /// <remarks/>
        Procurement_Plan_No,
        
        /// <remarks/>
        Creation_Date,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Category,
        
        /// <remarks/>
        Reference_No,
        
        /// <remarks/>
        Quotation_Deadline,
        
        /// <remarks/>
        Expected_Closing_Time,
        
        /// <remarks/>
        Committee_Submission_Date,
        
        /// <remarks/>
        Committee_Submission_Time,
        
        /// <remarks/>
        Termination_Date,
        
        /// <remarks/>
        Termination_Code,
        
        /// <remarks/>
        Termination_Reason,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Tender_Type,
        
        /// <remarks/>
        Submitted_To_Portal,
        
        /// <remarks/>
        Process_Type,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class Addendum_Registration {
        
        private string keyField;
        
        private string prospect_NoField;
        
        private string tender_NoField;
        
        private string name_of_the_FirmField;
        
        private string postal_AddressField;
        
        private string telephone_ContactsField;
        
        private string company_EmailField;
        
        private string contact_PersonField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Prospect_No {
            get {
                return this.prospect_NoField;
            }
            set {
                this.prospect_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Tender_No {
            get {
                return this.tender_NoField;
            }
            set {
                this.tender_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Name_of_the_Firm {
            get {
                return this.name_of_the_FirmField;
            }
            set {
                this.name_of_the_FirmField = value;
            }
        }
        
        /// <remarks/>
        public string Postal_Address {
            get {
                return this.postal_AddressField;
            }
            set {
                this.postal_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone_Contacts {
            get {
                return this.telephone_ContactsField;
            }
            set {
                this.telephone_ContactsField = value;
            }
        }
        
        /// <remarks/>
        public string Company_Email {
            get {
                return this.company_EmailField;
            }
            set {
                this.company_EmailField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_Person {
            get {
                return this.contact_PersonField;
            }
            set {
                this.contact_PersonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class Opening_Committee_Members {
        
        private string keyField;
        
        private string employee_NoField;
        
        private string nameField;
        
        private Role roleField;
        
        private bool roleFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Employee_No {
            get {
                return this.employee_NoField;
            }
            set {
                this.employee_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Role Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoleSpecified {
            get {
                return this.roleFieldSpecified;
            }
            set {
                this.roleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum Role {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Member,
        
        /// <remarks/>
        Chair,
        
        /// <remarks/>
        Secretary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class Tender_Addendum {
        
        private string keyField;
        
        private string descriptionField;
        
        private Type_3 typeField;
        
        private bool typeFieldSpecified;
        
        private string tender_NoField;
        
        private TypeAdd typeAddField;
        
        private bool typeAddFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Type_3 Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Tender_No {
            get {
                return this.tender_NoField;
            }
            set {
                this.tender_NoField = value;
            }
        }
        
        /// <remarks/>
        public TypeAdd TypeAdd {
            get {
                return this.typeAddField;
            }
            set {
                this.typeAddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeAddSpecified {
            get {
                return this.typeAddFieldSpecified;
            }
            set {
                this.typeAddFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum Type_3 {
        
        /// <remarks/>
        Scope_Parameter,
        
        /// <remarks/>
        Objective_Heading,
        
        /// <remarks/>
        Objective_Heading_End,
        
        /// <remarks/>
        Sub_Heading,
        
        /// <remarks/>
        Sub_Heading_End,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum TypeAdd {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Scope,
        
        /// <remarks/>
        Specifications,
        
        /// <remarks/>
        Addendum,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class Tender_Scope_of_Work {
        
        private string keyField;
        
        private string descriptionField;
        
        private Scope_Type scope_TypeField;
        
        private bool scope_TypeFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Scope_Type Scope_Type {
            get {
                return this.scope_TypeField;
            }
            set {
                this.scope_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Scope_TypeSpecified {
            get {
                return this.scope_TypeFieldSpecified;
            }
            set {
                this.scope_TypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum Scope_Type {
        
        /// <remarks/>
        Scope_Parameter,
        
        /// <remarks/>
        Objective_Heading,
        
        /// <remarks/>
        Objective_Heading_End,
        
        /// <remarks/>
        Sub_Heading,
        
        /// <remarks/>
        Sub_Heading_End,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public partial class Procurement_Request_Lines {
        
        private string keyField;
        
        private string item_Category_CodeField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string descriptionField;
        
        private string specification2Field;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string unit_of_MeasureField;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string procurement_PlanField;
        
        private string procurement_Plan_ItemField;
        
        private string budget_LineField;
        
        private decimal amount_LCYField;
        
        private bool amount_LCYFieldSpecified;
        
        private string requisition_NoField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Item_Category_Code {
            get {
                return this.item_Category_CodeField;
            }
            set {
                this.item_Category_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Specification2 {
            get {
                return this.specification2Field;
            }
            set {
                this.specification2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure {
            get {
                return this.unit_of_MeasureField;
            }
            set {
                this.unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified {
            get {
                return this.unit_PriceFieldSpecified;
            }
            set {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Procurement_Plan {
            get {
                return this.procurement_PlanField;
            }
            set {
                this.procurement_PlanField = value;
            }
        }
        
        /// <remarks/>
        public string Procurement_Plan_Item {
            get {
                return this.procurement_Plan_ItemField;
            }
            set {
                this.procurement_Plan_ItemField = value;
            }
        }
        
        /// <remarks/>
        public string Budget_Line {
            get {
                return this.budget_LineField;
            }
            set {
                this.budget_LineField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount_LCY {
            get {
                return this.amount_LCYField;
            }
            set {
                this.amount_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_LCYSpecified {
            get {
                return this.amount_LCYFieldSpecified;
            }
            set {
                this.amount_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Requisition_No {
            get {
                return this.requisition_NoField;
            }
            set {
                this.requisition_NoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tendercard")]
    public enum Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Resource,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        Charge_Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenderCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenderCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenderCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenderCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenderCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenderCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenderCard TenderCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenderCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenderCard[] TenderCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenderCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenderCard TenderCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenderCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TenderCard[] TenderCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TenderCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Delete_Control13CompletedEventHandler(object sender, Delete_Control13CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_Control13CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_Control13CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Delete_Control12CompletedEventHandler(object sender, Delete_Control12CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_Control12CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_Control12CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Delete_Tender_Scope_of_WorkCompletedEventHandler(object sender, Delete_Tender_Scope_of_WorkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_Tender_Scope_of_WorkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_Tender_Scope_of_WorkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Delete_Tender_AddendumCompletedEventHandler(object sender, Delete_Tender_AddendumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_Tender_AddendumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_Tender_AddendumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Delete_CommitteeCompletedEventHandler(object sender, Delete_CommitteeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_CommitteeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_CommitteeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Delete_AddendumCompletedEventHandler(object sender, Delete_AddendumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_AddendumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_AddendumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591